import Link from "next/link";
import { ArrowUpRight, Check, FileText, Images, LayoutDashboard, Settings, Users } from "lucide-react";
import { DemoNotice, Logo, MetaLine } from "../components";
import { getServerLocale } from "../server-locale";
import { tx } from "../i18n-shared";

export default function AdminPage() {
  const locale = getServerLocale();
  const reviewRows = locale === "ko" ? [["01", "장민서", "회화 · 서울", "12 Sep"], ["02", "아리 타카하시", "설치 · 도쿄", "10 Sep"], ["03", "노아 윌리엄스", "영상 · 런던", "08 Sep"]] : [["01", "Jang Minseo", "Painting · Seoul", "12 Sep"], ["02", "Ari Takahashi", "Installation · Tokyo", "10 Sep"], ["03", "Noah Williams", "Moving image · London", "08 Sep"]];
  const logs = locale === "ko" ? ["서유진 프로필 승인", "한미라가 새 작품 추가", "‘After the Salon’ 프로젝트 공개", "Glasshouse Gallery에서 제안 도착"] : ["Seo Yujin profile approved", "New work added by Han Mira", "Project ‘After the Salon’ published", "Proposal received from Glasshouse Gallery"];
  return <main className="admin-page"><DemoNotice /><div className="admin-wrap"><aside className="admin-nav"><Logo compact /><span className="dash-label">{tx(locale, "Admin / UNFRAME", "관리자 / UNFRAME")}</span><Link className="active" href="/admin"><LayoutDashboard size={16} /> {tx(locale, "Dashboard", "대시보드")}</Link><Link href="/artists"><Users size={16} /> {tx(locale, "Artists", "아티스트")} <b>3</b></Link><Link href="/works"><Images size={16} /> {tx(locale, "Works", "작품")}</Link><Link href="/projects"><FileText size={16} /> {tx(locale, "Projects", "프로젝트")}</Link><Link href="/admin"><Settings size={16} /> {tx(locale, "Settings", "설정")}</Link><div className="dash-bottom"><span>{tx(locale, "Super admin", "슈퍼 관리자")}</span><small>{tx(locale, "UID verified", "UID 인증됨")}</small></div></aside><section className="admin-main"><div className="admin-top"><div><MetaLine>{tx(locale, "ADMIN / DASHBOARD", "관리자 / 대시보드")}</MetaLine><h1>{tx(locale, <>The unit,<br /><em>in motion.</em></>, <>움직이는<br /><em>유닛.</em></>)}</h1></div><span className="admin-date">{tx(locale, "15 September 2026", "2026년 9월 15일")}</span></div><div className="admin-stats"><div><span>{tx(locale, "Approved artists", "승인된 아티스트")}</span><strong>24</strong><small>{tx(locale, "+4 this month", "이번 달 +4명")}</small></div><div><span>{tx(locale, "Works uploaded", "업로드된 작품")}</span><strong>186</strong><small>{tx(locale, "+21 this month", "이번 달 +21점")}</small></div><div><span>{tx(locale, "Open proposals", "열린 제안")}</span><strong>08</strong><small>{tx(locale, "2 need review", "2건 검토 필요")}</small></div><div><span>{tx(locale, "Active projects", "활성 프로젝트")}</span><strong>12</strong><small>{tx(locale, "3 in process", "3건 진행 중")}</small></div></div><div className="admin-columns"><section className="admin-table"><div className="admin-section-head"><div><MetaLine>{tx(locale, "REVIEW QUEUE", "검토 대기열")}</MetaLine><h2>{tx(locale, "Artist applications", "아티스트 신청")}</h2></div><Link href="/artists">{tx(locale, "View all", "모두 보기")} <ArrowUpRight size={14} /></Link></div>{reviewRows.map(row => <div className="review-row" key={row[1]}><span>{row[0]}</span><div><strong>{row[1]}</strong><small>{row[2]}</small></div><time>{row[3]}</time><button aria-label={`${tx(locale, "Approve", "승인")} ${row[1]}`}><Check size={15} /></button></div>)}</section><section className="admin-activity"><div className="admin-section-head"><div><MetaLine>{tx(locale, "RECENT LOG", "최근 기록")}</MetaLine><h2>{tx(locale, "What changed", "변경된 내용")}</h2></div></div>{logs.map((item, i) => <div className="log-row" key={item}><i /><p>{item}<small>{tx(locale, `${i + 1} hour${i ? "s" : ""} ago`, `${i + 1}시간 전`)}</small></p></div>)}</section></div></section></div></main>;
}
