import Link from "next/link";
import { ArrowUpRight, CalendarDays, MapPin, Sparkles } from "lucide-react";
import { DemoNotice, PageIntro, PageSection, SectionHeading } from "../components";
import { events, opportunities } from "../data";
import { getServerLocale } from "../server-locale";
import { tx } from "../i18n-shared";

export default function RadarPage() {
  const locale = getServerLocale();
  return <main><DemoNotice /><div className="page-wrap radar-page"><PageIntro className="radar-hero" bare /><PageSection sectionId="calendar"><section className="radar-section"><SectionHeading title={tx(locale, "On the calendar", "캘린더 위의 장면")} action={tx(locale, "Save a date", "일정 저장")} href="#events" /><div className="radar-event-list" id="events">{events.length === 0 ? <div className="empty-state"><h3>{tx(locale, "No public events yet.", "아직 공개된 일정이 없습니다.")}</h3><p>{tx(locale, "Published events will appear here when they are ready.", "공개된 일정이 준비되면 이곳에 나타납니다.")}</p></div> : events.map((event, index) => <article className="radar-event-row" key={event.slug}><span className="radar-index">0{index + 1}</span><div className="radar-date"><CalendarDays size={15} /><strong>{event.date}</strong><small>{event.status}</small></div><div><span className="meta-line">{event.kind} · {event.city}</span><h2>{event.title}</h2><p>{event.description}</p><div className="radar-people">{event.participants.map((participant) => <span key={participant}>{participant}</span>)}</div></div><button className="radar-save" type="button" aria-label={tx(locale, `Save ${event.title}`, `${event.title} 저장`)}>+</button></article>)}</div></section></PageSection><PageSection sectionId="opportunities"><section className="radar-section radar-opportunities"><SectionHeading title={tx(locale, "Open doors", "열려 있는 문")} action={tx(locale, "For artists", "아티스트를 위한 기회")} href="#opportunities" /><div className="opportunity-grid" id="opportunities">{opportunities.length === 0 ? <div className="empty-state"><h3>{tx(locale, "No public opportunities yet.", "아직 공개된 기회가 없습니다.")}</h3><p>{tx(locale, "Open calls and opportunities will appear here when they are published.", "공개 모집과 기회가 등록되면 이곳에 나타납니다.")}</p></div> : opportunities.map((opportunity) => <article className="opportunity-row" key={opportunity.slug}><div className="opportunity-top"><span>{opportunity.kind}</span><span>{opportunity.deadline}</span></div><h2>{opportunity.title}</h2><p>{opportunity.description}</p><div className="opportunity-bottom"><span><MapPin size={13} /> {opportunity.location}</span><span>{opportunity.organiser}</span></div><Link className="text-link" href={`/radar#${opportunity.slug}`}>{tx(locale, "Read the signal", "신호 읽기")} <ArrowUpRight size={14} /></Link></article>)}</div></section></PageSection><PageSection sectionId="note"><section className="radar-note"><Sparkles size={18} /><div><span className="meta-line">{tx(locale, "WHY THIS IS HERE", "이곳에 있는 이유")}</span><h2>{tx(locale, "No popularity contest. Just a sharper way in.", "인기 경쟁이 아닙니다. 더 선명하게 들어가는 방식입니다.")}</h2><p>{tx(locale, "The Radar is curated by the unit and built to lead to a person, a place, or a next move — not another endless feed.", "Radar는 유닛이 직접 선별하며, 끝없는 피드가 아니라 사람과 장소, 다음 움직임으로 이어지도록 만듭니다.")}</p></div></section></PageSection></div></main>;
}
