import Link from "next/link";
import { ArrowUpRight, Check } from "lucide-react";
import { MetaLine } from "../components";
import { getServerLocale } from "../server-locale";
import { tx } from "../i18n-shared";

export default function JoinPage() {
  const locale = getServerLocale();
  return <main><div className="page-wrap join-page"><div className="join-intro"><MetaLine>{tx(locale, "JOIN U.A.U", "u.a.u 함께하기")}</MetaLine><h1>{tx(locale, <>There is more than<br /><em>one way in.</em></>, <>들어오는 방법은<br /><em>하나가 아닙니다.</em></>)}</h1><p>{tx(locale, "Start with an account, a practice, a curiosity, or a reason to keep a door open.", "계정과 실천, 호기심, 혹은 계속 문을 열어둘 이유에서 시작하세요.")}</p></div><div className="join-options"><div><span className="join-icon">01</span><h2>{tx(locale, "I am an artist", "나는 아티스트입니다")}</h2><p>{tx(locale, "Build a profile, share your work, and join the relationships that begin through UNFRAME.", "프로필을 만들고 작품을 공유하며 UNFRAME을 통해 시작되는 관계에 함께하세요.")}</p><Link className="text-link" href="/login">{tx(locale, "Apply as an artist", "아티스트로 신청하기")} <ArrowUpRight size={14} /></Link></div><div><span className="join-icon">02</span><h2>{tx(locale, "I am looking", "찾고 있습니다")}</h2><p>{tx(locale, "Discover artists, save works, and make a thoughtful proposal when the moment is right.", "아티스트를 발견하고 작품을 저장하며, 적절한 순간에 사려 깊은 제안을 건네세요.")}</p><Link className="text-link" href="/artists">{tx(locale, "Explore the archive", "아카이브 둘러보기")} <ArrowUpRight size={14} /></Link></div><div><span className="join-icon">03</span><h2>{tx(locale, "I want to connect", "연결하고 싶습니다")}</h2><p>{tx(locale, "For curators, galleries, brands, and institutions looking for a practice — not just a name.", "이름만이 아니라 하나의 실천을 찾는 큐레이터, 갤러리, 브랜드, 기관을 위한 자리입니다.")}</p><a className="text-link" href="mailto:hello@uau.unframe.kr">{tx(locale, "Start a conversation", "대화 시작하기")} <ArrowUpRight size={14} /></a></div></div><div className="join-note"><Check size={15} /> {tx(locale, "Accounts are free. u.a.u Artist membership is reviewed by the UNFRAME team.", "계정은 무료입니다. u.a.u 아티스트 멤버십은 UNFRAME 팀의 검토를 거칩니다.")}</div></div></main>;
}
