import Link from "next/link";
import { ArrowUpRight, Check } from "lucide-react";
import { PageIntro, PageSection } from "../components";
import { getServerLocale } from "../server-locale";
import { tx } from "../i18n-shared";

export default function JoinPage() {
  const locale = getServerLocale();
  return <main><div className="page-wrap join-page"><PageIntro className="join-intro" bare /><PageSection sectionId="options"><div className="join-options"><div><span className="join-icon">01</span><h2>{tx(locale, "I am an artist", "나는 아티스트입니다")}</h2><p>{tx(locale, "Build a profile, share your work, and join the relationships that begin through UNFRAME.", "프로필을 만들고 작품을 공유하며 UNFRAME을 통해 시작되는 관계에 함께하세요.")}</p><Link className="text-link" href="/login">{tx(locale, "Apply as an artist", "아티스트로 신청하기")} <ArrowUpRight size={14} /></Link></div><div><span className="join-icon">02</span><h2>{tx(locale, "I am looking", "찾고 있습니다")}</h2><p>{tx(locale, "Discover artists, save works, and make a thoughtful proposal when the moment is right.", "아티스트를 발견하고 작품을 저장하며, 적절한 순간에 사려 깊은 제안을 건네세요.")}</p><Link className="text-link" href="/artists">{tx(locale, "Explore the archive", "아카이브 둘러보기")} <ArrowUpRight size={14} /></Link></div><div><span className="join-icon">03</span><h2>{tx(locale, "I want to connect", "연결하고 싶습니다")}</h2><p>{tx(locale, "For curators, galleries, brands, and institutions looking for a practice — not just a name.", "이름만이 아니라 하나의 실천을 찾는 큐레이터, 갤러리, 브랜드, 기관을 위한 자리입니다.")}</p><a className="text-link" href="mailto:hello@uau.unframe.kr">{tx(locale, "Start a conversation", "대화 시작하기")} <ArrowUpRight size={14} /></a></div></div></PageSection>
    <PageSection sectionId="membership-path"><div className="membership-path"><div className="membership-path-intro"><span>{tx(locale, "ARTIST MEMBERSHIP / A PRACTICE THAT OPENS OUTWARD", "ARTIST MEMBERSHIP / 작업이 바깥으로 이어지는 방식")}</span><h2>{tx(locale, <>Build your archive.<br/><em>Take it further.</em></>, <>기록을 쌓고,<br/><em>더 넓은 자리로.</em></>)}</h2><p>{tx(locale, "U.A.U membership is curated by UNFRAME. As your artist archive takes shape, practical tools become available and your work can enter editorial consideration.", "U.A.U 아티스트 멤버십은 언프레임의 검토를 거칩니다. 작가 아카이브가 갖춰지면 실무 도구를 활용하고 편집 기회에 도전할 수 있어요.")}</p></div><div className="membership-path-items"><article><span>PORTFOLIO / EXPORT</span><h3>{tx(locale, "A portfolio from the work you have already entered.", "입력한 기록으로 포트폴리오 PDF를.")}</h3><p>{tx(locale, "Complete your profile, CV, three selected works, and an exhibition record to print or save a portfolio PDF.", "프로필·CV·대표작 3점·전시 기록을 채우면 입력한 정보로 포트폴리오 PDF를 출력하거나 저장할 수 있습니다.")}</p><Link className="text-link" href="/dashboard/profile">{tx(locale, "Build your profile", "프로필 채우기")} <ArrowUpRight size={14}/></Link></article><article><span>VIRTUAL GALLERY / MEMBERSHIP</span><h3>{tx(locale, "A space that stays with your active artist access.", "활성 아티스트 이용 기간에 이어지는 전시장.")}</h3><p>{tx(locale, "Approved artists and active members can use the U.A.U virtual gallery while their artist access is active. Gallery tools and availability may evolve with the service.", "승인 아티스트와 활성 멤버는 아티스트 이용 권한이 활성화된 동안 U.A.U 버추얼 갤러리를 이용할 수 있습니다. 기능과 제공 범위는 서비스 운영에 따라 달라질 수 있어요.")}</p><Link className="text-link" href="/dashboard/virtual-gallery">{tx(locale, "Explore the gallery tools", "버추얼 갤러리 살펴보기")} <ArrowUpRight size={14}/></Link></article><article><span>ANNUAL ARCHIVE / EDITORIAL OPPORTUNITY</span><h3>{tx(locale, "Let a year of practice become an edition.", "한 해의 작업을 한 권의 기록으로.")}</h3><p>{tx(locale, "When UNFRAME produces an annual print archive, complete artist pages may be considered by the editorial team. Inclusion is curated, requires the artist’s consent, and is not guaranteed.", "언프레임이 연간 실물 아카이브를 제작할 경우, 충실히 완성된 작가 페이지는 편집팀 검토 후보가 될 수 있습니다. 수록은 별도 선정과 작가 동의를 거치며 보장되지 않습니다.")}</p><Link className="text-link" href="/dashboard/progress">{tx(locale, "See archive milestones", "아카이브 준비도 보기")} <ArrowUpRight size={14}/></Link></article></div></div></PageSection>
    <PageSection sectionId="note"><div className="join-note"><Check size={15} /> {tx(locale, "Accounts are free. u.a.u Artist membership is reviewed by the UNFRAME team.", "계정은 무료입니다. u.a.u 아티스트 멤버십은 UNFRAME 팀의 검토를 거칩니다.")}</div></PageSection></div></main>;
}
