import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, MoveUpRight } from "lucide-react";
import { ArtImage, BookmarkButton, DemoNotice, MetaLine, SectionHeading } from "./components";
import { annualRecap, artworks, events, journal, opportunities } from "./data";
import { ConnectionMarquee, RotatingWord } from "./motion-components";
import { HomeFaq } from "./components/home-faq";
import { NewlyConnected } from "./components/newly-connected";
import { getServerLocale } from "./server-locale";
import { artworkText, tx } from "./i18n-shared";
import { SiteCopy, SiteSection } from "./site-content";

export default function Home() {
  const locale = getServerLocale();
  const journalCopy = locale === "ko" ? [
    ["전시 이후", "방이 비었을 때 남는 것은 무엇인가?", "u.a.u 에디토리얼"],
    ["스튜디오 방문", "서유진은 거의 말해지지 않은 것의 기록을 남긴다", "박은지"],
    ["아티스트 레이더", "사이의 공간을 작업하는 5명의 아티스트", "u.a.u 에디토리얼"],
  ] : journal.map(entry => [entry.category, entry.title, entry.author]);
  return <main>
    <DemoNotice />
    <section className="hero-shell page-wrap">
      <div className="hero-copy"><p className="hero-kicker">u.a.u / UNFRAME ARTIST UNIT</p><h1><SiteCopy contentKey="home.hero.line1" fallback={locale === "ko" ? "관계가 계속되는" : "A network"} /><br /><em><SiteCopy contentKey="home.hero.emphasis" fallback={locale === "ko" ? "아티스트" : "that stays"} /></em><br /><SiteCopy contentKey="home.hero.line3" fallback={locale === "ko" ? "네트워크." : "connected."} /></h1><p className="hero-lede"><SiteCopy className="site-copy-preline" contentKey="home.hero.lede" fallback={locale === "ko" ? "전시에서 시작된 관계가\n그 이후에도 이어집니다." : "A relationship that starts in an exhibition\nand keeps going after."} /><br /><small><SiteCopy contentKey="home.hero.subline" fallback={locale === "ko" ? "연결과 지속을 중심으로 움직이는 글로벌 아티스트 네트워크." : "A global artist network built around connection and continuity."} /></small></p><div className="hero-actions"><Link className="button button-blue" href="/connections"><SiteCopy contentKey="home.hero.primary" fallback={locale === "ko" ? "연결 따라가기" : "Trace the connections"} /> <ArrowUpRight size={16} /></Link><Link className="underlined-link" href="/artists"><SiteCopy contentKey="home.hero.secondary" fallback={locale === "ko" ? "아티스트 만나기" : "Meet the artists"} /> <ArrowDownRight size={16} /></Link></div></div>
      <div className="hero-stage"><div className="hero-stage-label"><span>{tx(locale, "Featured work", "주목할 작품")}</span><span>01 / 04</span></div><ArtImage className="hero-art" loading="eager" label={tx(locale, "Abstract mixed-media artwork by Seo Yujin", "서유진의 추상 혼합 매체 작품")} /><div className="hero-caption"><div><strong>The Distance Between</strong><span>Seo Yujin · 2026</span></div><Link href="/works/the-distance-between" aria-label={tx(locale, "Open The Distance Between", "The Distance Between 열기")}><ArrowUpRight size={18} /></Link></div><div className="trace-line"><span className="trace-node node-a" /><span className="trace-node node-b" /><span className="trace-node node-c" /><span className="trace-label">{tx(locale, "connected through", "연결 경로")}<br /><b>UNFRAME Salon 04</b></span></div></div>
    </section>

    <section className="intro-band page-wrap" id="about"><div className="intro-title"><span>01</span><h2><SiteCopy className="site-copy-preline" contentKey="home.intro.title" fallback={locale === "ko" ? "아티스트는 실천으로 들어와\n관계로 남습니다." : "Artists enter through practice,\nremain through relationship."} /></h2></div><div className="intro-copy"><p><SiteCopy contentKey="home.intro.body" fallback={locale === "ko" ? "u.a.u는 UNFRAME을 통해 형성된 관계를 중심으로 움직이는 아티스트 유닛입니다. 전시를 넘어 지속적인 교류와 협업, 실천으로 이어갑니다." : "u.a.u is an artist unit built around relationships formed through UNFRAME — extending beyond exhibitions into ongoing exchange, collaboration and practice."} /></p><Link className="text-link" href="/connections"><SiteCopy contentKey="home.intro.cta" fallback={locale === "ko" ? "우리가 연결되는 방식" : "How we connect"} /> <ArrowUpRight size={14} /></Link></div></section>

    <ConnectionMarquee items={locale === "ko" ? ["서유진 · 아티스트", "UNFRAME 살롱 04 · 전시", "Glasshouse Gallery · 갤러리", "박은지 · 디렉터", "최미나 · 큐레이터", "이준 · 컬렉터", "한미라 · 아티스트", "After the Salon · 프로젝트"] : ["Seo Yujin · Artist", "UNFRAME Salon 04 · Exhibition", "Glasshouse Gallery · Gallery", "Eunji Park · Director", "Mina Choi · Curator", "Jun Lee · Collector", "Han Mira · Artist", "After the Salon · Project"]} />

    <SiteSection contentKey="home.section.radar"><section className="radar-home page-wrap"><div className="radar-home-heading"><div><MetaLine>{tx(locale, "U.A.U RADAR / OPEN ROOMS", "U.A.U RADAR / 열려 있는 방")}</MetaLine><h2><SiteCopy className="site-copy-preline" contentKey="home.radar.title" fallback={locale === "ko" ? "따라가 볼 만한\n신호." : "A signal worth\nfollowing."} /></h2></div><Link className="text-link" href="/radar"><SiteCopy contentKey="home.radar.cta" fallback={locale === "ko" ? "Radar 들어가기" : "Enter Radar"} /> <ArrowUpRight size={14} /></Link></div><div className="radar-home-grid"><Link className="radar-home-feature" href="/radar#events"><span>{events[0].kind} · {events[0].date}</span><h3>{events[0].title}</h3><p>{events[0].description}</p><b>{events[0].participants.join(" · ")} <ArrowUpRight size={14} /></b></Link><Link className="radar-home-feature radar-home-blue" href="/radar#opportunities"><span>{opportunities[0].kind} · {opportunities[0].deadline}</span><h3>{opportunities[0].title}</h3><p>{opportunities[0].description}</p><b>{tx(locale, "A door for artists", "아티스트를 위한 문") } <ArrowUpRight size={14} /></b></Link></div></section></SiteSection>

    <SiteSection contentKey="home.section.connection"><section className="page-wrap section-space"><SectionHeading title={tx(locale, "Current connection", "현재의 연결")} action={tx(locale, "View all connections", "모든 연결 보기")} href="/connections" /><div className="connection-feature"><div className="connection-people"><div className="person-mark tone-blue">SY</div><div className="connection-connector"><span>{tx(locale, "Exhibited with", "함께 전시")}</span><i /></div><div className="person-mark tone-ink">HM</div><div className="connection-connector"><span>{tx(locale, "Working alongside", "함께 작업")}</span><i /></div><div className="person-mark tone-clay">YD</div></div><div className="connection-story"><MetaLine>UNFRAME SALON 04 · SEOUL · 2026</MetaLine><h3>{tx(locale, <>What happens<br /><em>after the room empties?</em></>, <>방이 비워진 뒤<br /><em>무슨 일이 일어날까요?</em></>)}</h3><p>{tx(locale, "Three artists keep a conversation open across painting, textile, and sound. Their next meeting is taking shape now.", "세 명의 아티스트가 회화, 텍스타일, 사운드를 가로질러 대화를 이어갑니다. 다음 만남이 지금 만들어지고 있습니다.")}</p><Link className="text-link" href="/projects/after-the-salon">{tx(locale, "Follow the project", "프로젝트 따라가기")} <ArrowUpRight size={14} /></Link></div></div></section></SiteSection>

    <section className="recap-banner page-wrap"><div className="recap-copy"><MetaLine>{tx(locale, "ANNUAL CONNECTION RECAP / 2027", "연간 연결 리캡 / 2027")}</MetaLine><h2>{annualRecap.title}<br /><em>{tx(locale, "the year in connection.", "연결로 기록한 한 해.")}</em></h2><p>{tx(locale, annualRecap.intro, "관계가 방과 도시, 실천 사이를 오가며 다시 돌아갈 무언가를 남긴 한 해.")}</p><Link className="text-link" href="/recap">{tx(locale, "Enter the recap", "리캡 보기")} <ArrowUpRight size={14} /></Link></div><div className="recap-stats">{annualRecap.stats.map(([value, label], index) => <div key={label}><strong>{value}</strong><span>{tx(locale, label, ["유닛의 아티스트", "진행 중인 프로젝트", "새로운 연결", "연결된 도시"][index])}</span></div>)}</div></section>

    <section className="blue-panel page-wrap"><div className="panel-copy"><MetaLine>{tx(locale, "U.A.U SELECT / SEPTEMBER", "U.A.U 셀렉트 / 9월")}</MetaLine><h2>{tx(locale, <>New forms<br /><em>of being together.</em></>, <>함께 존재하는<br /><em>새로운 형식.</em></>)}</h2><p>{tx(locale, "A monthly selection by the UNFRAME team — artists, works, and the threads we keep noticing.", "UNFRAME 팀이 매달 고르는 아티스트와 작품, 그리고 우리가 계속 주목하는 연결의 실마리.")}</p><Link className="button button-light" href="/works">{tx(locale, "Enter the selection", "셀렉트 보기")} <ArrowUpRight size={16} /></Link></div><div className="panel-art"><ArtImage className="select-art" label={tx(locale, "Selected sculptural artwork", "선정된 조각 작품")} position="70% center" /><span className="panel-index">SELECT / 09</span></div></section>

    <section className="page-wrap section-space" id="artists"><SectionHeading title={tx(locale, "Newly connected", "새롭게 연결된 아티스트")} action={tx(locale, "All artists", "모든 아티스트")} href="/artists" /><p className="section-note">{tx(locale, "New practices entering the unit this week.", "이번 주 유닛에 새롭게 연결된 실천들입니다.")}</p><NewlyConnected locale={locale} /></section>

    <section className="page-wrap section-space works-section"><SectionHeading title={tx(locale, "Works to spend time with", "천천히 머물러 볼 작품")} action={tx(locale, "Discover all works", "모든 작품 보기")} href="/works" /><div className="works-grid">{artworks.slice(0, 3).map(work => { const copy = artworkText(locale, work.id)!; return <Link href={`/works/${work.id}`} className="work-card" key={work.id}><ArtImage className={`work-art ${work.accent}`} position={work.imagePosition} label={work.title} /><div className="work-info"><div><strong>{work.title}</strong><span>{work.artist} · {work.year}</span></div><BookmarkButton label="" /></div><MetaLine>{copy.medium}</MetaLine></Link>})}</div></section>

    <section className="journal-section page-wrap" id="journal"><SectionHeading title={tx(locale, "Journal / After the exhibition", "저널 / 전시 이후")} action={tx(locale, "Read the archive", "아카이브 읽기")} href="#journal" /><div className="journal-grid">{journal.map((entry, index) => <Link href="#journal" className={index === 0 ? "journal-entry journal-featured" : "journal-entry"} key={entry.title}><span className="journal-category">{journalCopy[index][0]}</span><h3>{journalCopy[index][1]}</h3><div><span>{journalCopy[index][2]}</span><span>{entry.date}</span><ArrowUpRight size={15} /></div></Link>)}</div></section>

    <HomeFaq locale={locale} />

    <section className="join-band page-wrap"><div><MetaLine>{tx(locale, "OPEN TO / ARTISTS · CURATORS · COLLECTORS", "열려 있는 대상 / 아티스트 · 큐레이터 · 컬렉터")}</MetaLine><h2>{tx(locale, "There is room for", "여기에는 자리가 있습니다")}<br /><RotatingWord words={locale === "ko" ? ["당신의 실천.", "다음 프로젝트.", "새로운 연결.", "그 다음에 올 것."] : ["your practice.", "your next project.", "a new connection.", "what comes next."]} /></h2></div><Link className="button button-blue" href="/join">{tx(locale, "Find your way in", "당신의 방식으로 들어오기")} <MoveUpRight size={16} /></Link></section>
  </main>;
}
