import Link from "next/link";
import { ArrowUpRight, CalendarDays, MapPin, Sparkles } from "lucide-react";
import { Breadcrumb, DemoNotice, MetaLine, SectionHeading } from "../components";
import { annualRecap } from "../data";
import { getServerLocale } from "../server-locale";
import { tx } from "../i18n-shared";

export default function RecapPage() {
  const locale = getServerLocale();
  const stats = locale === "ko" ? ["유닛의 아티스트", "진행 중인 프로젝트", "새로운 연결", "연결된 도시"] : annualRecap.stats.map(([, label]) => label);
  const awards = locale === "ko" ? [["올해의 연결", "After the Salon", "계속되기를 선택한 대화."], ["예상 밖의 유닛", "Soft Violence", "두 가지 물질, 하나의 느린 리듬."], ["경계를 넘어서", "서울 → 베를린 → 부산", "거리가 실천의 일부가 되었습니다."]] : annualRecap.awards;
  return <main><DemoNotice /><div className="page-wrap inner-page recap-page"><Breadcrumb current="Connected 2027" /><section className="recap-hero"><div><MetaLine>{tx(locale, "u.a.u ANNUAL CONNECTION RECAP", "u.a.u 연간 연결 리캡")}</MetaLine><h1>CONNECTED<br /><em>2027</em></h1><p>{tx(locale, annualRecap.intro, "관계가 방과 도시, 실천 사이를 오가며 다시 돌아갈 무언가를 남긴 한 해.")}</p><div className="recap-event-meta"><span><CalendarDays size={15} /> {tx(locale, "Annual record", "연간 기록")}</span><span><MapPin size={15} /> {tx(locale, "Seoul · Berlin · Busan", "서울 · 베를린 · 부산")}</span></div></div><div className="recap-orbit" aria-hidden="true"><span>u.a.u</span><i /><i /><i /><b>2027</b></div></section><section className="recap-stat-board"><div className="recap-stat-heading"><MetaLine>{tx(locale, "THE YEAR IN NUMBERS", "숫자로 보는 한 해")}</MetaLine><p>{tx(locale, "Not a leaderboard. A record of what moved between people.", "순위가 아닙니다. 사람 사이에서 움직인 것들의 기록입니다.")}</p></div>{annualRecap.stats.map(([value, label], index) => <div className="recap-stat" key={label}><strong>{value}</strong><span>{stats[index]}</span></div>)}</section><section className="recap-story"><SectionHeading title={tx(locale, "The thread this year", "올해의 실마리")} /><div><p>{tx(locale, "In 2027, the unit grew less by gathering names and more by making room for the next conversation. A studio visit became a shared reference. A show became a project. A city became a point on the map.", "2027년, 유닛은 이름을 모으기보다 다음 대화를 위한 자리를 만들며 자랐습니다. 스튜디오 방문은 공유된 레퍼런스가 되었고, 전시는 프로젝트가 되었으며, 도시는 지도의 한 점이 되었습니다.")}</p><p>{tx(locale, "These are the connections we are carrying forward.", "우리가 앞으로 이어갈 연결들입니다.")}</p><Link className="text-link" href="/connections">{tx(locale, "Open the connection map", "연결 지도 열기")} <ArrowUpRight size={14} /></Link></div></section><section className="recap-awards"><SectionHeading title={tx(locale, "Connection awards", "연결 어워드")} /><div className="award-list">{awards.map(([award, winner, description], index) => <div className="award-row" key={award}><span>0{index + 1}</span><div><MetaLine>{award}</MetaLine><h3>{winner}</h3><p>{description}</p></div><Sparkles size={16} /></div>)}</div></section><section className="recap-gathering"><MetaLine>{tx(locale, "CONNECTED 2027 / ANNUAL RECAP & GATHERING", "CONNECTED 2027 / 연간 리캡 & 모임")}</MetaLine><h2>{tx(locale, <>Come back<br /><em>for the next connection.</em></>, <>다음 연결을 위해<br /><em>다시 돌아오세요.</em></>)}</h2><Link className="button button-blue" href="/join">{tx(locale, "Find your way in", "당신의 방식으로 들어오기")} <ArrowUpRight size={16} /></Link></section></div></main>;
}
